### ISSUE TITLE
update vendir to v0.14

### ISSUE THREAD

**Issue by drnic** [k14s/homebrew-tap#6]
https://github.com/k14s/homebrew-tap/blob/develop/vendir.rb is on 0.13

**Comment by joaopapereira** [comment]
Hello, @drnic we were in the process of moving our tap into a different Github repository so this tap will no longer be available.
The newer versions of all the Carvel tools will be available under the tap `vmware-tanzu/carvel`. In order to update your homebrew, you need to do the following.

```
brew untap k14s/tap
brew tap vmware-tanzu/carvel
```

If the untap fails you might need to uninstall the applications you installed using the k14s/tap and you afterward can install them with the new tap.

**Comment by drnic** [comment]
Ok thanks, I've now switched over
